import { describe,expect,it } from 'vitest';import { games } from '../data/catalog';import { pokemonDataSource } from '../data/PokemonDataSource';import { combineDexItemsBySpecies,createDexSearchSuggestions,paginateDexGroups } from './dexView';
const species=(number:number)=>({id:`species-${number}`,nationalDexNumber:number,name:`Poke ${number}`,defaultFormId:`form-${number}`});const form=(number:number)=>({id:`form-${number}`,speciesId:`species-${number}`,name:'Standard',sprite:'sprite',types:['normal'] as const});
describe('Dex view pagination',()=>{
  const items=Array.from({length:31},(_,index)=>({species:species(index+1),form:form(index+1),dexNumber:index+1}));
  const boxes=paginateDexGroups({id:'national',label:null,items});

  it('creates 30-slot boxes without changing dex order',()=>{expect(boxes).toHaveLength(2);expect(boxes[0]?.items).toHaveLength(30);expect(boxes[1]?.items[0]?.dexNumber).toBe(31)});
  it('keeps the main occurrence and assigns sequential numbers to a combined game Dex',()=>{const first={species:species(1),form:form(1),dexNumber:1};const main={species:species(194),form:form(194),dexNumber:53};const duplicate={...main,form:{...form(194),id:'form-194-dlc'},dexNumber:159};const dlcOnly={species:species(34),form:form(34),dexNumber:70};expect(combineDexItemsBySpecies([first,main,duplicate,dlcOnly])).toEqual([first,{...main,dexNumber:2},{...dlcOnly,dexNumber:3}])});
  it('gives Nidoking a combined Sword and Shield number instead of its Crown Tundra number',()=>{const swsh=games.find(game=>game.id==='swsh')!;const speciesById=pokemonDataSource.getSpeciesById();const formsById=pokemonDataSource.getFormsById();const sections=swsh.dexSections!.filter(section=>section.showDexNumbers!==false);const items=sections.flatMap(section=>section.dexSpeciesIds.map((id,index)=>{const currentSpecies=speciesById.get(id)!;return {species:currentSpecies,form:formsById.get(section.formOverrides?.[id]??currentSpecies.defaultFormId)!,dexNumber:index+1}}));const combined=combineDexItemsBySpecies(items);const nidoking=combined.find(item=>item.species.id==='species-34')!;const crownTundraNumber=sections.find(section=>section.id==='crown-tundra')!.dexSpeciesIds.indexOf('species-34')+1;expect(nidoking.dexNumber).toBeGreaterThan(400);expect(nidoking.dexNumber).not.toBe(crownTundraNumber)});
  it('uses the current game Dex number in suggestions',()=>{const item={species:species(100),form:form(100),dexNumber:5};expect(createDexSearchSuggestions([item])).toEqual([{id:'species-100',name:'Poke 100',dexNumber:5}])});
});
