export const en={
  dashboard:'Dashboard',nationalDex:'National Dex',shinyDex:'Shiny Dex',regionalForms:'Regional Forms',specialForms:'Variants',backup:'Backup & restore',gameDexes:'Game Dexes',darkMode:'Dark mode',lightMode:'Light mode',saved:'Saved locally',search:'Search Pokémon or # number',all:'All',owned:'Owned',missing:'Missing',allOt:'All OT',ownOt:'Own OT',otherOt:'Other OT',generation:'Generation filter',alphaFilter:'Alpha filter',collectionView:'Collection view',shinyMode:'Shiny',normalMode:'Normal',typeFilter:'Type filter',language:'Language',
  close:'Close tutorial',skip:'Skip tutorial',next:'Next',start:'Start organizing',quickStart:'QUICK START',goToStep:'Go to step',
  complete:'Complete Dex',clear:'Clear Dex',completeForms:'Complete forms',clearForms:'Clear forms',dexCompletion:'Dex completion',formsCompletion:'Forms completion',completePercent:'complete',coreCollection:'CORE COLLECTION',gameCollection:'GAME COLLECTION',formCollection:'VARIANT COLLECTION',regionalCollection:'ALTERNATE HABITATS',
  searchEmpty:'No Pokémon match this search.',searchDescription:'Thirty slots per box, derived directly from your collection.',shinyDescription:'Only shiny collection entries count toward this view.',regionalDescription:'Regional forms remain connected to their National Dex species.',regionalShinyDescription:'Only shiny regional entries count toward this view.',specialDescription:'Checklists for species with multiple variant forms.',specialShinyDescription:'Only shiny variant form entries count toward this view.',
  added:'Pokémon added.',updated:'Collection updated.',entryUpdated:'Entry updated.',copyUpdated:'One copy updated.',quantityUpdated:'Quantity updated.',removed:'Entry removed.',entriesRemoved:'Entries removed.',restored:'Entry restored.',collectionUpdateError:'The collection could not be updated.',noEntriesRemoved:'No entries removed.',entryRemovedCount:'entry removed.',entriesRemovedCount:'entries removed.',entriesRestored:'Entries restored.',undo:'Undo',dismiss:'Dismiss notification',
  backupTitle:'Backup & restore',backupDescription:'Keep a portable copy of the collection stored on this device.',exportTitle:'Export collection',exportDescription:'Download a versioned JSON backup containing only your collection entries.',exportBackup:'Export backup',exportCsv:'Export CSV',importTitle:'Import backup',importDescription:'Select a Living Dex JSON file. Nothing changes until you review and confirm it.',selectJson:'Select JSON file',merge:'Merge collection',replace:'Replace collection',replaceCollection:'Replace collection',importPreview:'IMPORT PREVIEW',dataSafety:'DATA SAFETY',backupAndRestore:'Backup and restore',localStored:'Your collection is stored locally on this device.',backupExported:'Backup exported successfully.',backupExportError:'Could not export the collection.',csvExported:'CSV exported successfully.',csvExportError:'Could not export CSV.',backupReadError:'Could not read this backup. Check that the file is a valid Living Dex backup.',backupMerged:'Backup merged with your collection.',backupReplaced:'Collection replaced from backup.',backupImportError:'Could not import this backup.',species:'species',aggregatedEntries:'aggregated entries',exportedAt:'exported',duplicatesDetected:'duplicate records detected; quantities will be consolidated.',replaceCollectionQuestion:'Replace the current collection?',replaceCollectionDescription:'All entries currently stored on this device will be replaced by this backup. Export your current collection first if needed.',confirmation:'Confirmation',mergeCollectionQuestion:'Merge this backup with the current collection?',mergeCollectionDescription:'Backup entries will be combined with the entries stored on this device. Matching quantities will be consolidated.',
  form:'Form',formLower:'form',game:'Game',origin:'Origin',regular:'Regular',shiny:'✨ Shiny',alpha:'Alpha',notAlpha:'Not Alpha',total:'Total',otherOtStat:'Other OT',byGame:'By game',quickAdd:'Quick add',addOne:'Add one',entries:'Entries',filters:'Filters',changeForm:'Change the form of one copy',changeGame:'Change the game of one copy',changeOt:'Change the OT of one copy',changeShiny:'Change the shiny status of one copy',changeAlpha:'Change the Alpha status of one copy',removeOne:'Remove one',noCompatibleGame:'No compatible game',closePokemonDetails:'Close Pokémon details',
  clearRegional:'Clear all regional forms?',clearRegionalDescription:'Every regional form entry will be removed from your collection. This cannot be undone.',clearSpecial:'Clear all variant forms?',clearSpecialDescription:'Every entry represented in these variant form groups will be removed.',clearEntireDex:'Clear the entire Dex?',clearEntireDexDescription:'Every collection entry that contributes to this Dex will be removed, regardless of the active search or filter. This cannot be undone.',addAll:'Add all',addAllDescription:'Add one of each Pokémon in this box',clearBox:'Clear box',clearBoxQuestion:'Clear this box?',clearBoxDescription:'Every collection entry from this box that contributes to the current Dex will be removed. This cannot be undone.',clearBoxButtonDescription:'Set every Pokémon in this box to zero',cancel:'Cancel',destructiveAction:'Destructive action',closeConfirmation:'Close confirmation',
  collectionCompanion:'Collection companion',welcomeBack:'WELCOME BACK',collectionGlance:'Your collection, at a glance',dashboardDescription:'Every number updates from the Pokémon entries stored on this device.',nationalLivingDex:'National Living Dex',shinyLivingDex:'Shiny Living Dex',ownOtLivingDex:'Own OT Living Dex',supportedGames:'Species registered in each supported game',connectedDexes:'CONNECTED DEXES',gamesDescription:'Adding a Pokémon here also counts toward National progress.',uniqueSpecies:'unique species',openDex:'Open dex',gameProgress:'Game Dex Progress',backToTop:'Back to top',slotOwned:'owned',slotMissing:'missing',slotHint:'Click for details · Double-click or Space to add or remove one',
  onboardingOrganizeTitle:'Organize your Living Dex',onboardingOrganizeDescription:'Every Pokémon stays visible in 30-slot boxes, ordered by the selected Dex. Missing entries remain dimmed so you always know what is next.',onboardingUpdateTitle:'Update with a double click',onboardingUpdateDescription:'Double-click a slot to add one copy when it is missing, or remove one copy when you already have it. If origins differ, the details panel opens so you can choose the right entry.',onboardingVariantsTitle:'Track every variation',onboardingVariantsDescription:'Use Shiny Dex, Regional Forms and Variants to track alternate appearances. The same collection powers every view and game progress.',onboardingFindTitle:'Find and edit quickly',onboardingFindDescription:'Search by name or National Dex number, filter by generation, ownership and OT, then click a Pokémon to edit its form, game, OT, shiny status and quantity.',onboardingBackupTitle:'Keep your data safe',onboardingBackupDescription:'Your collection is stored locally on this device. Use Backup & restore to export a JSON copy and restore or merge it whenever you need.',
  variantUnownName:'Unown Alphabet',variantUnownDescription:'A–Z, ! and ?',variantRotomName:'Rotom Appliances',variantRotomDescription:'All appliance forms',variantFurfrouName:'Furfrou Trims',variantFurfrouDescription:'Natural and styled trims',variantFlabebeName:'Flabébé Line Colors',variantFlabebeDescription:'Flower color variations',
  type_normal:'Normal',type_fire:'Fire',type_water:'Water',type_electric:'Electric',type_grass:'Grass',type_ice:'Ice',type_fighting:'Fighting',type_poison:'Poison',type_ground:'Ground',type_flying:'Flying',type_psychic:'Psychic',type_bug:'Bug',type_rock:'Rock',type_ghost:'Ghost',type_dragon:'Dragon',type_dark:'Dark',type_steel:'Steel',type_fairy:'Fairy',
} as const;
export type TranslationKey=keyof typeof en;
