import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { CollectionEntry, CollectionEntryInput } from '../domain/models';
import { collectionService } from '../app/dependencies';
import { useToastStore } from '../store/toastStore';
import { useI18n } from '../i18n';
const key=['collection'] as const;
export function useCollection(){return useQuery({queryKey:key,queryFn:()=>collectionService.list()});}
export function useCollectionActions(){
 const {t}=useI18n();const client=useQueryClient();const show=useToastStore(state=>state.show);const success=(message:string)=>async()=>{await client.invalidateQueries({queryKey:key});show(message)};const error=()=>show(t('collectionUpdateError','The collection could not be updated.'),'error');
 const add=useMutation({mutationFn:(input:CollectionEntryInput)=>collectionService.add(input),onSuccess:success(t('added','Pokémon added.')),onError:error});
 const addMany=useMutation({mutationFn:(inputs:CollectionEntryInput[])=>collectionService.addOrIncrementMany(inputs),onSuccess:success(t('updated','Collection updated.')),onError:error});
 const update=useMutation({mutationFn:({id,changes}:{id:string;changes:Partial<CollectionEntryInput>})=>collectionService.update(id,changes),onSuccess:success(t('entryUpdated','Entry updated.')),onError:error});
 const changeOne=useMutation({mutationFn:({id,changes}:{id:string;changes:Partial<CollectionEntryInput>})=>collectionService.changeOne(id,changes),onSuccess:success(t('copyUpdated','One copy updated.')),onError:error});
 const changeQuantity=useMutation<{removed?:CollectionEntry},Error,{id:string;quantity:number}>({mutationFn:async({id,quantity})=>{const entry=client.getQueryData<CollectionEntry[]>(key)?.find(candidate=>candidate.id===id);await collectionService.changeQuantity(id,quantity);return {removed:quantity<=0?entry:undefined}},onSuccess:async(data)=>{await client.invalidateQueries({queryKey:key});if(data.removed){const entry=data.removed;show(t('removed','Entry removed.'),'success',{label:t('undo','Undo'),onClick:async()=>{const input:CollectionEntryInput={speciesId:entry.speciesId,formId:entry.formId,shiny:entry.shiny,alpha:entry.alpha,gameId:entry.gameId,ownOT:entry.ownOT,quantity:entry.quantity,originGameId:entry.originGameId};await collectionService.add(input);await client.invalidateQueries({queryKey:key});show(t('restored','Entry restored.'))}})}else show(t('quantityUpdated','Quantity updated.'))},onError:error});
 const remove=useMutation({mutationFn:(id:string)=>collectionService.remove(id),onSuccess:success(t('removed','Entry removed.')),onError:error});
 const removeMany=useMutation<CollectionEntry[],Error,string[]>({mutationFn:async(ids)=>{const entries=client.getQueryData<CollectionEntry[]>(key)??[];const removed=entries.filter(entry=>ids.includes(entry.id));await collectionService.removeMany(ids);return removed},onSuccess:async(removed)=>{await client.invalidateQueries({queryKey:key});if(!removed.length){show(t('noEntriesRemoved','No entries removed.'));return}show(`${removed.length} ${t(removed.length===1?'entryRemovedCount':'entriesRemovedCount',removed.length===1?'entry removed.':'entries removed.')}`,'success',{label:t('undo','Undo'),onClick:async()=>{await collectionService.addOrIncrementMany(removed.map(entry=>({speciesId:entry.speciesId,formId:entry.formId,gameId:entry.gameId,originGameId:entry.originGameId,shiny:entry.shiny,alpha:entry.alpha,ownOT:entry.ownOT,quantity:entry.quantity})));await client.invalidateQueries({queryKey:key});show(t('entriesRestored','Entries restored.'))}})},onError:error});
 return {add,addMany,update,changeOne,changeQuantity,remove,removeMany};
}
