import { Plus, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { ConfirmButton } from '../components/ConfirmButton';
import { DexFilters } from '../components/DexFilters';
import { PokemonBox } from '../components/PokemonBox';
import { PokemonDetails } from '../components/PokemonDetails';
import { ProgressBar } from '../components/ProgressBar';
import { pokemonDataSource } from '../data/PokemonDataSource';
import { isAlphaEligibleSpecies } from '../domain/alpha';
import { indexCollectionEntries } from '../domain/collection';
import type { OtFilter, PokemonForm } from '../domain/models';
import { createDexSearchSuggestions } from '../domain/dexView';
import { isInTypes } from '../domain/types';
import { useCollection } from '../hooks/useCollection';
import { useDexCollectionActions } from '../hooks/useDexCollectionActions';
import { useDexFilters } from '../hooks/useDexFilters';
import { useI18n, type TranslationKey } from '../i18n';
import { useUiStore } from '../store/uiStore';
import { useProvideSearchSuggestions } from '../store/searchSuggestionsStore';

export function SpecialFormsPage(){
  const {data:entries=[]}=useCollection();
  const {selectedFormId,selectForm,search,searchTargetSpeciesId,setSearch}=useUiStore();
  const {t}=useI18n();
  const {shiny,setShiny,alpha,setAlpha,ownership,setOwnership,selectedTypes,toggleType,shinyValue}=useDexFilters();
  const [ot,setOt]=useState<OtFilter>('all');
  const speciesById=pokemonDataSource.getSpeciesById();
  const formsById=pokemonDataSource.getFormsById();
  const games=pokemonDataSource.getGames();
  const groups=pokemonDataSource.getFormGroups();
  const entryIndex=useMemo(()=>indexCollectionEntries(entries,{shiny,alpha,ot}),[entries,shiny,alpha,ot]);
  const {quickToggle,addForms,clearForms}=useDexCollectionActions({entries,entryIndex,gameId:'home',ot,shiny,alpha,onSelect:selectForm});
  const eligible=(form:PokemonForm)=>isAlphaEligibleSpecies(games,form.speciesId);
  const activeGroups=groups.map(group=>({...group,formIds:group.formIds.filter(id=>{const form=formsById.get(id);return !!form&&(alpha!=='alpha'||eligible(form))&&isInTypes(form.types,selectedTypes)})}));
  const groupFormIds=new Set(activeGroups.flatMap(group=>group.formIds));
  const obtained=new Set(entryIndex.entries.filter(entry=>entry.quantity>0&&groupFormIds.has(entry.formId)).map(entry=>entry.formId)).size;
  const total=groupFormIds.size;
  const percentage=total?Math.round(obtained/total*1000)/10:0;
  const visible=(form:PokemonForm)=>{const owned=(entryIndex.byFormId.get(form.id)??[]).some(entry=>entry.quantity>0);return ownership==='all'||(ownership==='owned'?owned:!owned)};
  const visibleGroups=activeGroups.map(group=>({group,items:group.formIds.map(id=>formsById.get(id)).filter((form):form is PokemonForm=>!!form&&visible(form)).map(form=>({form,species:speciesById.get(form.speciesId)!}))}));
  const searchSuggestions=createDexSearchSuggestions(visibleGroups.flatMap(group=>group.items));
  useProvideSearchSuggestions(searchSuggestions);
  const searchTargetGroup=searchTargetSpeciesId?visibleGroups.find(({items})=>items.some(item=>item.species.id===searchTargetSpeciesId)):undefined;
  const displayedGroups=searchTargetSpeciesId?(searchTargetGroup?[searchTargetGroup]:[]):visibleGroups;
  const addGroup=(items:{form:PokemonForm}[])=>addForms(items.map(item=>item.form),form=>alpha!=='alpha'||eligible(form));
  const clearGroup=(items:{form:PokemonForm}[])=>clearForms(items.map(item=>item.form));
  const allItems=activeGroups.flatMap(group=>group.formIds.map(id=>formsById.get(id)).filter((form):form is PokemonForm=>!!form).map(form=>({form})));
  const selected=selectedFormId?formsById.get(selectedFormId):undefined;
  const groupKeys:Partial<Record<string,{name:TranslationKey;description:TranslationKey}>>={unown:{name:'variantUnownName',description:'variantUnownDescription'},'burmy-line':{name:'variantBurmyLineName',description:'variantBurmyLineDescription'},rotom:{name:'variantRotomName',description:'variantRotomDescription'},basculin:{name:'variantBasculinName',description:'variantBasculinDescription'},'deerling-line':{name:'variantDeerlingLineName',description:'variantDeerlingLineDescription'},'flabebe-line':{name:'variantFlabebeName',description:'variantFlabebeDescription'},furfrou:{name:'variantFurfrouName',description:'variantFurfrouDescription'},oricorio:{name:'variantOricorioName',description:'variantOricorioDescription'},lycanroc:{name:'variantLycanrocName',description:'variantLycanrocDescription'},urshifu:{name:'variantUrshifuName',description:'variantUrshifuDescription'},squawkabilly:{name:'variantSquawkabillyName',description:'variantSquawkabillyDescription'},tatsugiri:{name:'variantTatsugiriName',description:'variantTatsugiriDescription'},'poltchageist-line':{name:'variantPoltchageistLineName',description:'variantPoltchageistLineDescription'}};
  return <><div className="page-head dex-page-head"><div><span className="eyebrow">{t('formCollection')}</span><h1>{t('specialForms','Variants')}</h1><p>{shiny==='shiny'?t('specialShinyDescription','Only shiny variant form entries count toward this view.'):t('specialDescription','Checklists for species with multiple variant forms.')}</p></div><div className="page-head-side"><div className="dex-progress-summary"><div><span>{t('formsCompletion','Forms completion')}</span><strong>{obtained} / {total}</strong></div><ProgressBar value={percentage}/><small>{percentage}% {t('completePercent')}</small></div><div className="dex-actions"><button onClick={()=>addGroup(allItems)}><Plus size={16}/> {t('completeForms','Complete forms')}</button><ConfirmButton className="danger" title={t('clearSpecial','Clear all variant forms?')} description={t('clearSpecialDescription','Every entry represented in these variant form groups will be removed.')} confirmLabel={t('clearForms','Clear forms')} onConfirm={()=>clearGroup(allItems)}><Trash2 size={16}/> {t('clearForms','Clear forms')}</ConfirmButton></div></div></div><DexFilters search={search} onSearch={setSearch} shiny={shiny} onShiny={setShiny} alpha={alpha} onAlpha={setAlpha} ownership={ownership} onOwnership={setOwnership} ot={ot} onOt={setOt} selectedTypes={selectedTypes} onType={toggleType}/>{displayedGroups.map(({group,items})=>{const keys=groupKeys[group.id];const title=keys?`${t(keys.name)} · ${t(keys.description)}`:`${group.name} · ${group.description}`;return items.length?<PokemonBox key={group.id} title={title} items={items} entryIndex={entryIndex} formsById={formsById} shiny={shinyValue} searchTargetSpeciesId={searchTargetSpeciesId} onSelect={form=>selectForm(form.id)} onQuickAdd={quickToggle} onAddAll={()=>addGroup(items)} onRemoveAll={()=>clearGroup(items)}/>:null})}{selected&&<PokemonDetails form={selected} entries={entries} onClose={()=>selectForm(null)}/>}</>;
}
