import { useUiStore } from './store/uiStore';
export type Language='en'|'pt-BR';
const translations={
  'pt-BR':{
    dashboard:'Dashboard',nationalDex:'National Dex',shinyDex:'Shiny Dex',regionalForms:'Regional Forms',specialForms:'Special Forms',backup:'Backup & restore',gameDexes:'Game Dexes',darkMode:'Dark mode',lightMode:'Light mode',saved:'Saved locally',search:'Search Pokémon or # number',all:'All',owned:'Owned',missing:'Missing',allOt:'All OT',ownOt:'Own OT',otherOt:'Other OT',generation:'Generation filter',close:'Close tutorial',skip:'Skip tutorial',next:'Next',start:'Start organizing',quickStart:'QUICK START',complete:'Complete Dex',clear:'Clear Dex',completeForms:'Complete forms',clearForms:'Clear forms',dexCompletion:'Dex completion',formsCompletion:'Forms completion',coreCollection:'CORE COLLECTION',gameCollection:'GAME COLLECTION',formCollection:'FORM COLLECTIONS',searchEmpty:'No Pokémon match this search.',added:'Pokémon added.',updated:'Collection updated.',entryUpdated:'Entry updated.',copyUpdated:'One copy updated.',quantityUpdated:'Quantity updated.',removed:'Entry removed.',entriesRemoved:'Entries removed.',restored:'Entry restored.',searchDescription:'Thirty slots per box, derived directly from your collection.',shinyDescription:'Only shiny collection entries count toward this view.',regionalDescription:'Regional forms remain connected to their National Dex species.',specialDescription:'Generic checklists for species with multiple alternate forms.',backupTitle:'Backup & restore',backupDescription:'Keep a portable copy of the collection stored on this device.',exportTitle:'Export collection',exportDescription:'Download a versioned JSON backup containing only your collection entries.',importTitle:'Import backup',importDescription:'Select a Living Dex JSON file. Nothing changes until you review and confirm it.',selectJson:'Select JSON file',merge:'Merge collection',replace:'Replace collection',importPreview:'IMPORT PREVIEW',dismiss:'Dismiss notification',undo:'Undo',form:'Form',game:'Game',origin:'Origin',regular:'Regular',shiny:'✨ Shiny',total:'Total',otherOtStat:'Other OT',byGame:'By game',quickAdd:'Quick add',addOne:'Add one',entries:'Entries',filters:'Filters',changeForm:'Change the form of one copy',changeGame:'Change the game of one copy',backupAndRestore:'Backup and restore',dataSafety:'DATA SAFETY',formsProgress:'Forms completion',localStored:'Your collection is stored locally on this device.'
  }
} as const;
const extraPt:Record<string,string>={dashboard:'Dashboard',darkMode:'Modo escuro',lightMode:'Modo claro',saved:'Salvo localmente',search:'Pesquisar Pokémon ou número #',all:'Todos',owned:'Obtidos',missing:'Faltantes',allOt:'Todos OT',ownOt:'Meu OT',otherOt:'Outro OT',generation:'Filtro por geração',complete:'Completar Dex',clear:'Limpar Dex',completeForms:'Completar formas',clearForms:'Limpar formas',dexCompletion:'Conclusão da Dex',formsCompletion:'Conclusão das formas',searchEmpty:'Nenhum Pokémon corresponde à pesquisa.',added:'Pokémon adicionado.',updated:'Coleção atualizada.',entryUpdated:'Entrada atualizada.',copyUpdated:'Uma cópia atualizada.',quantityUpdated:'Quantidade atualizada.',removed:'Entrada removida.',entriesRemoved:'Entradas removidas.',restored:'Entrada restaurada.',searchDescription:'Trinta slots por box, derivados diretamente da sua coleção.',shinyDescription:'Apenas entradas shiny contam nesta visualização.',regionalDescription:'As formas regionais continuam conectadas à espécie da National Dex.',specialDescription:'Checklists genéricos para espécies com várias formas alternativas.',backupDescription:'Mantenha uma cópia portátil da coleção armazenada neste dispositivo.',exportTitle:'Exportar coleção',exportDescription:'Baixe um backup JSON versionado contendo apenas suas entradas.',exportBackup:'Exportar backup',importTitle:'Importar backup',importDescription:'Selecione um arquivo JSON da Living Dex. Nada muda até você revisar e confirmar.',selectJson:'Selecionar arquivo JSON',merge:'Mesclar coleção',replace:'Substituir coleção',importPreview:'PRÉVIA DA IMPORTAÇÃO',byGame:'Por jogo',quickAdd:'Adição rápida',addOne:'Adicionar um',entries:'Entradas',changeForm:'Alterar a forma de uma cópia',changeGame:'Alterar o jogo de uma cópia',dataSafety:'SEGURANÇA DOS DADOS',localStored:'Sua coleção fica armazenada localmente neste dispositivo.',gameProgress:'Espécies registradas em cada jogo compatível',exported:'Backup exportado com sucesso.',replaceCollection:'Substituir coleção'};
export function useI18n(){const language=useUiStore(state=>state.language);const t=(key:string,fallback:string)=>language==='pt-BR'?(extraPt[key]??translations['pt-BR'][key as keyof typeof translations['pt-BR']]??fallback):fallback;return {language,t}}
Object.assign(extraPt,{regionalShinyDescription:'Apenas entradas regionais shiny contam nesta visualização.',specialShinyDescription:'Apenas entradas de formas shiny contam nesta visualização.',clearRegional:'Limpar todas as formas regionais?',clearRegionalDescription:'Todas as entradas de formas regionais serão removidas da sua coleção. Essa ação não pode ser desfeita.',clearSpecial:'Limpar todas as formas especiais?',clearSpecialDescription:'Todas as entradas representadas nestes grupos de formas serão removidas.'});
